FROM node:17.9.1-alpine3.15 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:17.9.1-alpine3.15
COPY --from=build-stage /app .
ENTRYPOINT [ "npm", "start" ]